# Numpy 
Numpy is used for statistical operations in python
It is one of the most popular python libraries
Deals with n dimensional vectors (arrays)

Advantages:
1. Extension to Python of multi dimensional arrays
2. Hardware efficient
3. Designed for scientific computation

In [4]:
import numpy as np

# Create a numpy array (vector)
a = np.array([0, 1, 2, 3, 4, 5])
a

array([0, 1, 2, 3, 4, 5])

In [5]:
# Print the type of values the array holds
a.dtype

dtype('int32')

In [6]:
# Create a numpy array from 0..to n
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# To create an arange array of specific data type
a = np.arange(10, dtype="double")
print("Double array", a)
# 0. -> 0.0

Double array [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [8]:
# Create an array using arange with start (inclusive) and end (exclusive) value and step size
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [10]:
# Create an array raised to some power
a2 = a ** 2
a2

array([ 1,  9, 25, 49, 81], dtype=int32)

In [13]:
# Get the dimension of the np array
a.ndim

1

In [15]:
# 2-D array (Matrix)
b = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])
print(b)

[[1 2 3 4]
 [3 4 5 6]]


In [16]:
# Fetch the shape of np array
print(b.shape)  # (a,b) a rows and b columns
print(a.shape)  # (a,) a elements

(2, 4)
(20,)


In [21]:
# 3-D arrays (Tensor)
c = np.array([[[1, 2], [2, 3]], [[3, 4], [4, 5]], [[5, 6], [6, 7]]])
print("Array : \n",c, "\n\n","Number of dimension", c.ndim,
      "\n Shape", c.shape)

Array : 
 [[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]

 [[5 6]
  [6 7]]] 

 Number of dimension 3 
 Shape (3, 2, 2)


### Link Space
Create vector using link space
 
method : linspace

arg0 : start value

arg1 : end value

Both inclusive

arg3 : Total number of values

In [22]:
a = np.linspace(1, 10, 25)
print(a)

[ 1.     1.375  1.75   2.125  2.5    2.875  3.25   3.625  4.     4.375
  4.75   5.125  5.5    5.875  6.25   6.625  7.     7.375  7.75   8.125
  8.5    8.875  9.25   9.625 10.   ]


In [23]:
# Create an one matrix/ multi dimensional array
a = np.ones((3, 3))  # 3x3 one matrix
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
a = np.ones((2, 3, 4))  # 2x3x4 one matrix
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [26]:
# Create a 0 value matrix. Always create decimal point values
a = np.zeros((3, 3))  # 3x3 zero matrix
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
a = np.zeros((2, 3, 4))  # 2x3x4 zero matrix
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [28]:
# Create an identity matrix
a = np.eye(3)  # 3x3 zero matrix
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
# Create diagonal arrays
a = np.diag([1, 2, 3, 4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
# Fetch diagonal values from a diagonal array in the form of a vector
print(np.diag(a))  # a is a diagonal matrix

In [31]:
# Create a random array of given shape
# THis will generate a vector of 4 uniformly     distributed random no
print("Random vector : ", np.random.rand(5))

Random vector :  [0.18006999 0.65431195 0.08612773 0.11536983 0.691534  ]


In [32]:
print("Random Integer vector : ", np.random.randint(0, 10, 5))

Random Integer vector :  [4 3 5 4 9]


In [33]:
print("Random matrix : ", np.random.rand(2, 3))

Random matrix :  [[0.27888023 0.78795832 0.24192125]
 [0.18437966 0.37479757 0.01892918]]


In [34]:
# Standard normal variant / caution distributed random no
print("Random vector : ", np.random.randn(5))

Random vector :  [ 0.37523163 -2.79154235 -1.72830116  0.19181684 -0.52337923]


In [35]:
# Create array of complex numbers (complex128)
c = np.array([2 + 1j, 9.0 + 4.5j])
print("Complex array : ", c, c.dtype)

Complex array :  [2.+1.j  9.+4.5j] complex128


In [36]:
# Boolean array (bool)
b = np.array([True, False, False, False, True])
print("Boolean array : ", b, b.dtype)

Boolean array :  [ True False False False  True] bool


In [37]:
# String array
s = np.array(["Hey", "how", "are", "you"])
print("String array : ", s, s.dtype)

String array :  ['Hey' 'how' 'are' 'you'] <U3


### Indexing in numpy arrays
We can manipulate and access numpy array elements through indexes the same way we do with normal arrays

Also the indexes start from 0 to length-1

In [38]:
# A random array
a = np.random.rand(5)
print("5th element : ", a[4])

5th element :  0.9294379098025841


In [39]:
# A 2D array
a = np.diag([1, 2, 3, 4])
print("Element at 3nd row and 3rd column : ", a[2, 2])

Element at 3nd row and 3rd column :  3


In [40]:
# Assigning values by index
a[2, 2] = 4
print("Element at 3nd row and 3rd column : ", a[2, 2])

Element at 3nd row and 3rd column :  4


In [44]:
# Fetch values at given index
a = np.arange(0, 25)

# Fetch only even indexed values
index = [i for i in range(0, a.__len__(), 3)]
print("Custom indexed a :", a[index])

Custom indexed a : [ 0  3  6  9 12 15 18 21 24]


In [45]:
# Assign values to given index
a[index] = -2
print("Changed indexed a :", a)

Changed indexed a : [-2  1  2 -2  4  5 -2  7  8 -2 10 11 -2 13 14 -2 16 17 -2 19 20 -2 22 23
 -2]


### Slicing 
It is similar to how we did it in normal arrays

In [46]:
# Sample array
a = np.arange(10)

# slice using indices ( start and end index (exclusive) and step size)
print("a[1:8:2] : ", a[1:8:2])

a[1:8:2] :  [1 3 5 7]


In [47]:
# Slicing and assignment: Assign values to all the elements from index 5
a[5:] = 10
print("a :", a)

a : [ 0  1  2  3  4 10 10 10 10 10]


In [48]:
# Assign reverse of an array to another
b = np.arange(5)
a[5:] = b[::-1]
print("Mix a :", a)

Mix a : [0 1 2 3 4 4 3 2 1 0]


In [49]:
# Masking : Filter through the array elements using a masking operation
a = np.arange(20)
# Create a  mask (operation on array)
# It is an bool array representing truth values for each element over the given operation
mask = ((a ** 2) % 4 == 0)
mask_output = a[mask]
print("Mask output:", mask_output)

Mask output: [ 0  2  4  6  8 10 12 14 16 18]


In [50]:
# Make changes to the masked values
# That is, make changes to values that satisfy the mask operation as a whole
a[mask] = -1
print("Final mask : ", a)

Final mask :  [-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19]
